<?php

/**
 * aBlogSlideshowSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aBlogSlideshowSlotTable extends PluginaBlogSlideshowSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aBlogSlideshowSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aBlogSlideshowSlot');
    }
}