<?php

/**
 * aMapSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aMapSlotTable extends PluginaMapSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aMapSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aMapSlot');
    }
}