imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: sonata.yml }
    - { resource: cmf.yml }
    - { resource: fos.yml }

parameters:
    cmf_blog.post_admin_class: Vespolina\SiteBundle\Admin\Blog\PostAdmin
    cmf_content.multilang.admin_class: Vespolina\SiteBundle\Admin\Content\StaticAdmin
    cmf_block.multilang.simple_admin_class: Vespolina\SiteBundle\Admin\Block\SimpleAdmin

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: v1 # Capifony updates this with the hash of the current release
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [FMElfinderBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        path:     "%database_path%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

#    orm:
#        entity_managers:
#            default:
#                connection: default
#                auto_mapping: true

doctrine_phpcr:
    session:
        backend:
            type: doctrinedbal
            connection: doctrine.dbal.default_connection
            caches:
                meta: liip_doctrine_cache.ns.meta
                nodes: liip_doctrine_cache.ns.nodes
        workspace: default
        username: admin
        password: admin
    odm:
        auto_mapping: true
        mappings:
            SonataMediaBundle:
                prefix: Sonata\MediaBundle\PHPCR
        locales:
            en: ~
        image:
            imagine_filter: false

# jackalope doctrine caching
liip_doctrine_cache:
    namespaces:
        meta:
            type: file_system
#            type: apc
        nodes:
#            type: file_system
            type: apc

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

trsteel_ckeditor:
    filebrowser_image_browse_url:
        route: elfinder
    contents_css:
        - /bundles/vespolinasite/css/bootstrap/bootstrap.min.css
        - /bundles/vespolinasite/css/app.css

fm_elfinder:
    locale: %locale%
    editor: ckeditor # other choices are tinymce or simple
    showhidden: false
    connector:
        debug: false # defaults to false
        roots:       # at least one root must be defined
            uploads:
                driver: LocalFileSystem
                path: uploads/content
                upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'image/gif', 'application/pdf', 'application/zip', 'application/octet-stream']
                upload_deny: ['all']
                upload_max_size: 20M